name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --windowed PolyRemote.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PolyRemote-Executable
        path: dist/PolyRemote.exe

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Build v1.0.${{ github.run_number }}
        body: |
          Build automático desde commit ${{ github.sha }}
        files: dist/PolyRemote.exe
